
package com.yusufeker.javaMailApp;

import com.formdev.flatlaf.FlatDarculaLaf;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import javax.swing.event.UndoableEditEvent;
import javax.swing.event.UndoableEditListener;
import javax.swing.undo.UndoManager;

/**
 * @author grievous
 **/
public class mailApp extends javax.swing.JFrame {

    /**
     * Creates new form newApp
    **/
    public mailApp() {
        initComponents();
        
        // removes white outline of message area
        //jScrollPane1.setBorder(BorderFactory.createEmptyBorder());
        //jScrollPane2.setBorder(BorderFactory.createEmptyBorder());
        
        this.setLocationRelativeTo(null); // centers the app in screen
        
        // Title of the app (like in taskbar)
        String appTitle = "Yusuf's Mail App";
        this.setTitle(appTitle);
                
        /*ImageIcon logo = new ImageIcon(getClass().
                                       getClassLoader().
                                       getResource("email.jpg"));
        this.setIconImage(logo.getImage());*/
        
        // Setting the icon of the application
        // I know, it was not set up in a very efficient and smooth way, but
        // of all the codes I wrote, only this one worked
        //ImageIcon img = new ImageIcon("C:\\Users\\grievous\\Documents\\NetBeansProjects\\javaMail\\res\\mail-app-icon-large.png");
        //this.setIconImage(img.getImage());
        Image img = new ImageIcon(this.getClass().getResource("/mail-app-icon-mini.png")).getImage();
        this.setIconImage(img);
        
        // Adding placeholder styles
        placeholder.addTextFieldPlaceholder(fromInput);
        placeholder.addTextFieldPlaceholder(passwordInput);
        placeholder.addTextFieldPlaceholder(toInput);
        placeholder.addTextFieldPlaceholder(subjectInput);
        placeholder.addTextAreaPlaceholder(messageInput);

        messageInput.getDocument().addUndoableEditListener(
                new UndoableEditListener() {
            public void undoableEditHappened(UndoableEditEvent e) {
                undoManager.addEdit(e.getEdit()); 
                // This is basically a format to add undo-redo function to text area
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new com.k33ptoo.components.KGradientPanel();
        fromHeader = new javax.swing.JLabel();
        passwordHeader = new javax.swing.JLabel();
        toHeader = new javax.swing.JLabel();
        subjectHeader = new javax.swing.JLabel();
        messageHeader = new javax.swing.JLabel();
        fromInput = new javax.swing.JTextField();
        passwordInput = new javax.swing.JPasswordField();
        toInput = new javax.swing.JTextField();
        subjectInput = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageInput = new javax.swing.JTextArea();
        redoBtn = new com.k33ptoo.components.KButton();
        undoBtn = new com.k33ptoo.components.KButton();
        sendMailBtn = new com.k33ptoo.components.KButton();
        mailProviderChooser = new javax.swing.JComboBox<>();
        addAttachBtn = new com.k33ptoo.components.KButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        attachmentPathList = new javax.swing.JTextArea();
        newGmailAccount = new javax.swing.JLabel();
        newMicrosoftAccount = new javax.swing.JLabel();
        newYahooAccount = new javax.swing.JLabel();
        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        topPanel = new javax.swing.JPanel();
        minimizeApp = new javax.swing.JLabel();
        inAppLogo = new javax.swing.JLabel();
        inAppName = new javax.swing.JLabel();
        closeApp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        background.setkEndColor(new java.awt.Color(0, 61, 116));
        background.setkGradientFocus(0);
        background.setkStartColor(new java.awt.Color(32, 33, 36));

        fromHeader.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        fromHeader.setForeground(new java.awt.Color(255, 255, 255));
        fromHeader.setText("From : ");

        passwordHeader.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        passwordHeader.setForeground(new java.awt.Color(255, 255, 255));
        passwordHeader.setText("Password : ");

        toHeader.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        toHeader.setForeground(new java.awt.Color(255, 255, 255));
        toHeader.setText("To : ");

        subjectHeader.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        subjectHeader.setForeground(new java.awt.Color(255, 255, 255));
        subjectHeader.setText("Subject : ");

        messageHeader.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        messageHeader.setForeground(new java.awt.Color(255, 255, 255));
        messageHeader.setText("Message : ");

        fromInput.setBackground(new Color(0,0,0,0));
        fromInput.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fromInput.setForeground(new java.awt.Color(255, 255, 255));
        fromInput.setText("Your Mail Address");
        fromInput.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 4, new java.awt.Color(32, 33, 36)));
        fromInput.setCaretColor(new java.awt.Color(255, 0, 0));
        fromInput.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        fromInput.setSelectionColor(new java.awt.Color(0, 61, 116));
        fromInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fromInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fromInputFocusLost(evt);
            }
        });

        passwordInput.setBackground(new Color(0,0,0,0));
        passwordInput.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        passwordInput.setForeground(new java.awt.Color(255, 255, 255));
        passwordInput.setText("Your Password");
        passwordInput.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 4, new java.awt.Color(32, 33, 36)));
        passwordInput.setCaretColor(new java.awt.Color(255, 0, 0));
        passwordInput.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        passwordInput.setEchoChar('\u0000');
        passwordInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordInputFocusLost(evt);
            }
        });

        toInput.setBackground(new Color(0,0,0,0));
        toInput.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        toInput.setForeground(new java.awt.Color(255, 255, 255));
        toInput.setText("Reciever Mail Address");
        toInput.setToolTipText("You can send mail to unlimited reciever!");
        toInput.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 4, new java.awt.Color(32, 33, 36)));
        toInput.setCaretColor(new java.awt.Color(255, 0, 0));
        toInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                toInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                toInputFocusLost(evt);
            }
        });

        subjectInput.setBackground(new Color(0,0,0,0));
        subjectInput.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        subjectInput.setForeground(new java.awt.Color(255, 255, 255));
        subjectInput.setText("Mail Subject");
        subjectInput.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 4, new java.awt.Color(32, 33, 36)));
        subjectInput.setCaretColor(new java.awt.Color(255, 0, 0));
        subjectInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                subjectInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                subjectInputFocusLost(evt);
            }
        });

        messageInput.setBackground(new java.awt.Color(32, 33, 36));
        messageInput.setColumns(20);
        messageInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        messageInput.setForeground(new java.awt.Color(255, 255, 255));
        messageInput.setLineWrap(true);
        messageInput.setRows(5);
        messageInput.setText("Your Message");
        messageInput.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));
        messageInput.setCaretColor(new java.awt.Color(255, 0, 0));
        messageInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                messageInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                messageInputFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(messageInput);

        redoBtn.setBorder(null);
        redoBtn.setForeground(new java.awt.Color(0, 61, 116));
        redoBtn.setText("Redo");
        redoBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        redoBtn.setkBackGroundColor(new java.awt.Color(255, 0, 0));
        redoBtn.setkEndColor(new java.awt.Color(0, 61, 116));
        redoBtn.setkForeGround(new java.awt.Color(32, 33, 36));
        redoBtn.setkHoverColor(new java.awt.Color(255, 0, 0));
        redoBtn.setkHoverEndColor(new java.awt.Color(0, 61, 116));
        redoBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        redoBtn.setkHoverStartColor(new java.awt.Color(32, 33, 36));
        redoBtn.setkIndicatorColor(new java.awt.Color(255, 0, 0));
        redoBtn.setkPressedColor(new java.awt.Color(32, 33, 36));
        redoBtn.setkSelectedColor(new java.awt.Color(255, 0, 0));
        redoBtn.setkStartColor(new java.awt.Color(255, 255, 255));
        redoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redoBtnActionPerformed(evt);
            }
        });

        undoBtn.setBorder(null);
        undoBtn.setForeground(new java.awt.Color(0, 61, 116));
        undoBtn.setText("Undo");
        undoBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        undoBtn.setkBackGroundColor(new java.awt.Color(255, 0, 0));
        undoBtn.setkEndColor(new java.awt.Color(0, 61, 116));
        undoBtn.setkForeGround(new java.awt.Color(32, 33, 36));
        undoBtn.setkHoverColor(new java.awt.Color(255, 0, 0));
        undoBtn.setkHoverEndColor(new java.awt.Color(0, 61, 116));
        undoBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        undoBtn.setkHoverStartColor(new java.awt.Color(32, 33, 36));
        undoBtn.setkIndicatorColor(new java.awt.Color(255, 0, 0));
        undoBtn.setkPressedColor(new java.awt.Color(32, 33, 36));
        undoBtn.setkSelectedColor(new java.awt.Color(255, 0, 0));
        undoBtn.setkStartColor(new java.awt.Color(255, 255, 255));
        undoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoBtnActionPerformed(evt);
            }
        });

        sendMailBtn.setBorder(null);
        sendMailBtn.setText("Send Mail");
        sendMailBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        sendMailBtn.setkBackGroundColor(new java.awt.Color(255, 0, 0));
        sendMailBtn.setkEndColor(new java.awt.Color(0, 61, 116));
        sendMailBtn.setkForeGround(new java.awt.Color(32, 33, 36));
        sendMailBtn.setkHoverColor(new java.awt.Color(255, 0, 0));
        sendMailBtn.setkHoverEndColor(new java.awt.Color(0, 61, 116));
        sendMailBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        sendMailBtn.setkHoverStartColor(new java.awt.Color(32, 33, 36));
        sendMailBtn.setkIndicatorColor(new java.awt.Color(255, 0, 0));
        sendMailBtn.setkPressedColor(new java.awt.Color(32, 33, 36));
        sendMailBtn.setkSelectedColor(new java.awt.Color(255, 0, 0));
        sendMailBtn.setkStartColor(new java.awt.Color(255, 255, 255));
        sendMailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendMailBtnActionPerformed(evt);
            }
        });

        mailProviderChooser.setBackground(new java.awt.Color(32, 33, 36));
        mailProviderChooser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mailProviderChooser.setForeground(new java.awt.Color(255, 255, 255));
        mailProviderChooser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "@gmail.com", "@live.com", "@outlook.com", "@hotmail.com", "@yahoo.com" }));
        mailProviderChooser.setBorder(null);

        addAttachBtn.setBorder(null);
        addAttachBtn.setText("Add Attachment");
        addAttachBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        addAttachBtn.setkBackGroundColor(new java.awt.Color(255, 0, 0));
        addAttachBtn.setkEndColor(new java.awt.Color(0, 61, 116));
        addAttachBtn.setkForeGround(new java.awt.Color(32, 33, 36));
        addAttachBtn.setkHoverColor(new java.awt.Color(255, 0, 0));
        addAttachBtn.setkHoverEndColor(new java.awt.Color(0, 61, 116));
        addAttachBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        addAttachBtn.setkHoverStartColor(new java.awt.Color(32, 33, 36));
        addAttachBtn.setkIndicatorColor(new java.awt.Color(255, 0, 0));
        addAttachBtn.setkPressedColor(new java.awt.Color(32, 33, 36));
        addAttachBtn.setkSelectedColor(new java.awt.Color(255, 0, 0));
        addAttachBtn.setkStartColor(new java.awt.Color(255, 255, 255));
        addAttachBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAttachBtnActionPerformed(evt);
            }
        });

        attachmentPathList.setEditable(false);
        attachmentPathList.setBackground(new java.awt.Color(32, 33, 36));
        attachmentPathList.setColumns(20);
        attachmentPathList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        attachmentPathList.setForeground(new java.awt.Color(255, 255, 255));
        attachmentPathList.setLineWrap(true);
        attachmentPathList.setRows(5);
        attachmentPathList.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));
        jScrollPane2.setViewportView(attachmentPathList);

        newGmailAccount.setForeground(new java.awt.Color(255, 255, 255));
        newGmailAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/google.png"))); // NOI18N
        newGmailAccount.setText("Google");
        newGmailAccount.setToolTipText("Google");
        newGmailAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newGmailAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newGmailAccountMouseClicked(evt);
            }
        });

        newMicrosoftAccount.setForeground(new java.awt.Color(255, 255, 255));
        newMicrosoftAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/microsoft.png"))); // NOI18N
        newMicrosoftAccount.setText("Microsoft");
        newMicrosoftAccount.setToolTipText("Microsoft");
        newMicrosoftAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newMicrosoftAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newMicrosoftAccountMouseClicked(evt);
            }
        });

        newYahooAccount.setForeground(new java.awt.Color(255, 255, 255));
        newYahooAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yahoo.png"))); // NOI18N
        newYahooAccount.setText("Yahoo");
        newYahooAccount.setToolTipText("Yahoo");
        newYahooAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newYahooAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newYahooAccountMouseClicked(evt);
            }
        });

        kGradientPanel1.setForeground(new java.awt.Color(32, 33, 36));
        kGradientPanel1.setkEndColor(new java.awt.Color(0, 61, 116));
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 255, 255));

        jLabel2.setForeground(new java.awt.Color(32, 33, 36));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Create New Account");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addContainerGap())
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        topPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        topPanel.setOpaque(false);
        topPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                topPanelMouseDragged(evt);
            }
        });
        topPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                topPanelMousePressed(evt);
            }
        });

        minimizeApp.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        minimizeApp.setForeground(new java.awt.Color(255, 255, 255));
        minimizeApp.setText("‒");
        minimizeApp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizeApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeAppMouseClicked(evt);
            }
        });

        inAppLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mail-app-icon-mini.png"))); // NOI18N

        inAppName.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        inAppName.setForeground(new java.awt.Color(255, 255, 255));
        inAppName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inAppName.setText("Mail Application w/Java");
        inAppName.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));

        closeApp.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        closeApp.setForeground(new java.awt.Color(255, 255, 255));
        closeApp.setText("X");
        closeApp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeAppMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(inAppLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inAppName)
                .addGap(106, 106, 106)
                .addComponent(minimizeApp)
                .addGap(18, 18, 18)
                .addComponent(closeApp)
                .addGap(30, 30, 30))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(inAppLogo))
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(closeApp)
                                .addComponent(minimizeApp))
                            .addComponent(inAppName))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(passwordHeader)
                                .addComponent(fromHeader)
                                .addComponent(toHeader)
                                .addComponent(subjectHeader))
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(messageHeader)))
                        .addGap(44, 44, 44)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fromInput)
                            .addComponent(passwordInput)
                            .addComponent(toInput)
                            .addComponent(subjectInput, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sendMailBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(newGmailAccount)
                                .addGap(18, 18, 18)
                                .addComponent(newMicrosoftAccount)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addComponent(undoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(redoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(newYahooAccount))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addAttachBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mailProviderChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
            .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mailProviderChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fromHeader)
                        .addComponent(fromInput, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passwordHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(toHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(toInput, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(subjectHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(subjectInput, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(messageHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(addAttachBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sendMailBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(redoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(undoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(newGmailAccount)
                        .addComponent(newMicrosoftAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(newYahooAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendMailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendMailBtnActionPerformed
        attachmentANDmessage.sendMailBtn(evt);
    }//GEN-LAST:event_sendMailBtnActionPerformed

    private void addAttachBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAttachBtnActionPerformed
        attachmentANDmessage.addAttachBtn(evt);
    }//GEN-LAST:event_addAttachBtnActionPerformed

    private void undoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoBtnActionPerformed
        undoRedo_Edit.undo(); // undo the text on message area
    }//GEN-LAST:event_undoBtnActionPerformed

    private void redoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redoBtnActionPerformed
        undoRedo_Edit.redo(); // redo the text on message area
    }//GEN-LAST:event_redoBtnActionPerformed

    private void closeAppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeAppMouseClicked
        System.exit(0); // shut down app
    }//GEN-LAST:event_closeAppMouseClicked

    private void minimizeAppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeAppMouseClicked
        this.setState(this.ICONIFIED); // minimize the app
    }//GEN-LAST:event_minimizeAppMouseClicked

    private void fromInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fromInputFocusGained
        placeholder.fromFocusGained(evt); // remove pleaceholder when focus gained
    }//GEN-LAST:event_fromInputFocusGained

    private void fromInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fromInputFocusLost
        placeholder.fromFocusLost(evt); // create pleaceholder when focus lost
    }//GEN-LAST:event_fromInputFocusLost

    private void passwordInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordInputFocusGained
        placeholder.passwordFocusGained(evt); // remove pleaceholder when focus gained
    }//GEN-LAST:event_passwordInputFocusGained

    private void passwordInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordInputFocusLost
        placeholder.passwordFocusLost(evt); // create pleaceholder when focus lost
    }//GEN-LAST:event_passwordInputFocusLost

    private void toInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_toInputFocusGained
        placeholder.toFocusGained(evt); // remove pleaceholder when focus gained
    }//GEN-LAST:event_toInputFocusGained

    private void toInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_toInputFocusLost
        placeholder.toFocusLost(evt); // create pleaceholder when focus lost
    }//GEN-LAST:event_toInputFocusLost

    private void subjectInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_subjectInputFocusGained
        placeholder.subjectFocusGained(evt); // remove pleaceholder when focus gained
    }//GEN-LAST:event_subjectInputFocusGained

    private void subjectInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_subjectInputFocusLost
        placeholder.subjectFocusLost(evt); // create pleaceholder when focus lost
    }//GEN-LAST:event_subjectInputFocusLost

    private void messageInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_messageInputFocusGained
        placeholder.messageFocusGained(evt); // remove pleaceholder when focus gained
    }//GEN-LAST:event_messageInputFocusGained

    private void messageInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_messageInputFocusLost
        placeholder.messageFocusLost(evt); // create pleaceholder when focus lost
    }//GEN-LAST:event_messageInputFocusLost

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        placeholder.formWindowGainedFocus(evt);
    }//GEN-LAST:event_formWindowGainedFocus

    private void newGmailAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newGmailAccountMouseClicked
        //createAccount.createNewGoogleAccount();
        accountCreator.main("google"); // send google to account creator factory
    }//GEN-LAST:event_newGmailAccountMouseClicked

    private void newMicrosoftAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newMicrosoftAccountMouseClicked
        //createAccount.createNewMicrosoftAccount();
        accountCreator.main("microsoft"); // send microsoft to account creator factory
    }//GEN-LAST:event_newMicrosoftAccountMouseClicked

    private void newYahooAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newYahooAccountMouseClicked
        //createAccount.createNewYahooAccount();
        accountCreator.main("yahoo"); // send yahoo to account creator factory
    }//GEN-LAST:event_newYahooAccountMouseClicked

    private void topPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topPanelMousePressed
        moveApp.getLocaction(evt); // when mouse is pressed call this method
    }//GEN-LAST:event_topPanelMousePressed

    private void topPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topPanelMouseDragged
        moveApp.changeLocaction(evt); // when mouse is dragging call this method
    }//GEN-LAST:event_topPanelMouseDragged

    protected List<File> attachmentList = new ArrayList<File>();
    UndoManager undoManager = new UndoManager();
    UndoRedo_Edit undoRedo_Edit = new UndoRedo_Edit(this);
    MoveApp moveApp = new MoveApp(this);
    AttachmentAndMessage attachmentANDmessage = new AttachmentAndMessage(this);
    Placeholder placeholder = new Placeholder(this);
    
    AccountCreator accountCreator = new AccountCreator(this);
    CreateAccount createAccount = new CreateAccount(this);
    
    /*  
    Add fullscreen button
    
    Add delete attachment
        
    Make it responsive for fullscreen
        
    Create undo-redo button with memento pattern for message area

    Make the design "from \n mail", not "from: email"
        
    Add logging on every send mail button click
    
    Add custom JOptionPane and it will send string where it is used and 
    that sent string will be printed inside the error box
    */
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        /*try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("".equals(info.getName())) {
        javax.swing.UIManager.setLookAndFeel(info.getClassName());
        break;
        }
        }
        } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(mailApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(mailApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(mailApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(mailApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        
        //</editor-fold>
        //</editor-fold>
        
        try {
            UIManager.setLookAndFeel(new FlatDarculaLaf());
        } catch (Exception e) {
            e.printStackTrace();
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mailApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton addAttachBtn;
    protected javax.swing.JTextArea attachmentPathList;
    private com.k33ptoo.components.KGradientPanel background;
    private javax.swing.JLabel closeApp;
    private javax.swing.JLabel fromHeader;
    protected javax.swing.JTextField fromInput;
    private javax.swing.JLabel inAppLogo;
    private javax.swing.JLabel inAppName;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    protected javax.swing.JComboBox<String> mailProviderChooser;
    private javax.swing.JLabel messageHeader;
    protected javax.swing.JTextArea messageInput;
    private javax.swing.JLabel minimizeApp;
    private javax.swing.JLabel newGmailAccount;
    private javax.swing.JLabel newMicrosoftAccount;
    private javax.swing.JLabel newYahooAccount;
    private javax.swing.JLabel passwordHeader;
    protected javax.swing.JPasswordField passwordInput;
    private com.k33ptoo.components.KButton redoBtn;
    private com.k33ptoo.components.KButton sendMailBtn;
    private javax.swing.JLabel subjectHeader;
    protected javax.swing.JTextField subjectInput;
    private javax.swing.JLabel toHeader;
    protected javax.swing.JTextField toInput;
    private javax.swing.JPanel topPanel;
    private com.k33ptoo.components.KButton undoBtn;
    // End of variables declaration//GEN-END:variables
}
